[package]
name = "host-component-macro"
version = "0.0.1"
authors = ["rickihastings"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0.11", features = ["full"] }
quote = "1.0"
