[package]
name = "host-component"
version = "0.1.0"
authors = ["rickihastings"]
edition = "2018"

[dependencies]
js-sys = "0.3.27"
treexml = "0.7"
wasm-bindgen = "0.2"
gloo-events = "0.1.1"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
  'Document',
  'Element',
  'Event',
  'EventTarget',
  'HtmlElement',
  'Node',
  'Window'
]
